### ISSUE TITLE
Output images get slightly corrupted

### ISSUE THREAD

**Issue by theCapypara** [Aikku93/tilequant#1]
Hi, first: Thanks for this tool!

I literally searched weeks for a tool like this and didn't find anything useful. In the end I built something myself, and I only found your tool now, because it by chance uses literally the same name (what are the odds?):
https://github.com/SkyTemple/tilequant

It uses a much more naive approach (since I have no experience in working with colors), where I just run a basic quantization algorithm over the image and then try to see if I can fit all of the tiles' colors into YxZ palettes. It's obviously MUCH slower than your solution and has a much smaller color resolution.

**Now the actual issue for this issue:**
Your tool seems to corrupt the output BMPs slightly, do you know what could cause this?

![kitteh2_o](https://user-images.githubusercontent.com/3512122/76961619-f5fa2180-691d-11ea-97c9-32dde9eb4ff1.png)

Also, would you be interested in some feature requests / adjustments for this tool? I'm trying to find something that works with the images for Pokémon Mystery Dungeon Explorers of Sky, and they are a bit special, because they also have one bit of transparency at the beginning of each palette. 
I supported this in my tool, by specifying one "transparent" color in the import image and then masking this and reserving the first color slot of all palettes for this transparent color.

Also I'd like to use your tool in my ROM editor, would it be possible to create some kind of C ABI interface for directly working with the raw pixels and color values?

I can also open additional issues for this or maybe we could discuss this on something like Discord. Of course I also understand if you don't have the time / or don't want to work on this project anymore :)

**Comment by theCapypara** [comment]
I figured out, that the issue was the format of the BMP (GIMP creates 32bit BMPs with embeded color profiles by default). I switches to 24bit without embeded color profiles and it works now. Not sure which of the two options it was.

As a side note, I integrated your Tilequant into my Python library now using the command line interface and it works great! Again, thanks for this algorithm!

**Comment by Aikku93** [comment]
Ah geez, I still have no idea how to use Github apparently - I only just found this.

"they also have one bit of transparency at the beginning of each palette" As in, for example, "For a 16-colour palette, entry 0 is transparent?" Atm, the tool is configured to always treat the first entry of a palette as fully transparent (consistent with GBA/NDS and I think SNES too)... with the caveat being that the opacity/alpha must be part of a 32bit BMP.

I can try and integrate an API (similar to how I added this to my audio codec project), but I'm not sure if that's what you meant, since you mention "ABI" instead. I'm guessing this is a Python thing to hook into lower-level programming?

Feel free to add me on Discord if you're up to working on this; I can be found as Aikku93#0976
